# Generated by Django 5.2.5 on 2026-01-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField()),
                ("company", models.CharField()),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Досвід",
                "verbose_name_plural": "Досвід",
                "ordering": ["-start_date", "company"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField()),
                ("description", models.TextField()),
                (
                    "technologies",
                    models.CharField(help_text="через кому: Python, JS, Postgres"),
                ),
                ("data", models.DateField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="projects/"),
                ),
                ("github_url", models.URLField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Проект",
                "verbose_name_plural": "Проекти",
                "ordering": ["-data", "title"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                (
                    "level",
                    models.PositiveSmallIntegerField(default=50, help_text="0-100"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("soft", "Soft"),
                            ("frontend", "Frontend"),
                            ("backend", "Backend"),
                            ("devops", "DevOps"),
                        ],
                        default="backend",
                    ),
                ),
            ],
            options={
                "verbose_name": "Навик",
                "verbose_name_plural": "Навички",
                "ordering": ["-level", "name"],
            },
        ),
    ]
